name: Delete Certificate

on:
  workflow_dispatch:  # Allows manually triggering the workflow

jobs:
  delete_certificate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # You can specify the Ruby version you are using

    - name: Install Fastlane
      run: |
        gem install bundler
        bundle install
      working-directory: .

    - name: Authenticate with Apple Developer Portal
      run: |
        bundle exec fastlane delete_certificate
      env:
        FASTLANE_USER: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
        FASTLANE_PASSWORD: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
        FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
        FASTLANE_ITC_TEAM_ID: ${{ secrets.FASTLANE_ITC_TEAM_ID }}

